name: glitch_rises
channels:
  - defaults
  - conda-forge
dependencies:
  - ffmpeg=4.2.2
  - jupyter=1.0.0
  - matplotlib=3.7.1
  - nb_conda_kernels=2.3.1
  - pandas=1.5.3
  - python=3.11.3
  - scipy=1.10.1
